// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package kratoscore

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/liujitcn/kratos-core/biz"
	"github.com/liujitcn/kratos-core/config"
	"github.com/liujitcn/kratos-core/internal/data"
	"github.com/liujitcn/kratos-core/internal/job"
	"github.com/liujitcn/kratos-core/internal/mcp"
	queue2 "github.com/liujitcn/kratos-core/internal/queue"
	"github.com/liujitcn/kratos-core/internal/resource"
	biz2 "github.com/liujitcn/kratos-core/internal/resource/biz"
	"github.com/liujitcn/kratos-core/internal/resource/i18n"
	"github.com/liujitcn/kratos-core/internal/resource/migration"
	"github.com/liujitcn/kratos-core/internal/resource/openapi"
	"github.com/liujitcn/kratos-core/internal/server"
	"github.com/liujitcn/kratos-core/internal/sse"
	"github.com/liujitcn/kratos-core/module"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/queue"
)

// Injectors from wire.go:

// NewApp 通过 Core ProviderSet 装配多个业务模块。
func NewApp(ctx *bootstrap.Context, modules ...module.Module) (*kratos.App, func(), error) {
	configv1Bootstrap, err := config.ParseBootstrap(ctx)
	if err != nil {
		return nil, nil, err
	}
	v, err := config.ParseDatabase(configv1Bootstrap)
	if err != nil {
		return nil, nil, err
	}
	moduleModules := module.NewModules(modules...)
	v2 := module.NewResources(moduleModules)
	models := module.NewModels(v2)
	v3, cleanup, err := biz.NewClients(v, models)
	if err != nil {
		return nil, nil, err
	}
	migrations := module.NewMigrations(v2)
	migrationMigration, err := migration.NewMigration(ctx, v3, migrations)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	openAPI := module.NewOpenAPIFromResources(v2)
	registry, err := openapi.NewRegistry(openAPI)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, err := data.NewData(v3)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseAPIRepository := data.NewBaseAPIRepository(dataData)
	baseAPII18nRepository := data.NewBaseAPII18nRepository(dataData)
	baseAPICase := biz2.NewBaseAPICase(baseAPIRepository, baseAPII18nRepository)
	baseRoleRepository := data.NewBaseRoleRepository(dataData)
	baseTenantRepository := data.NewBaseTenantRepository(dataData)
	baseTenantCase := biz2.NewBaseTenantCase(dataData, baseRoleRepository, baseTenantRepository)
	casbinRuleRepository := data.NewCasbinRuleRepository(dataData)
	baseMenuRepository := data.NewBaseMenuRepository(dataData)
	engine, err := biz.NewAuthzEngine()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	casbinRuleCase, err := biz2.NewCasbinRuleCase(casbinRuleRepository, baseMenuRepository, baseRoleRepository, baseTenantRepository, baseAPICase, engine)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	syncResult, err := resource.NewSyncResult(ctx, migrationMigration, registry, dataData, baseAPICase, baseTenantCase, casbinRuleCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appInfo := config.ParseAppInfo(ctx)
	authentication_Jwt, err := config.ParseAuthnJWT(configv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authenticator, err := biz.NewAuthenticator(authentication_Jwt)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseUserRepository := data.NewBaseUserRepository(dataData)
	data_Redis := config.ParseRedis(configv1Bootstrap)
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userToken := biz.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	moduleI18n := module.NewI18nFromResources(v2)
	i18nI18n, err := i18n.NewCatalog(moduleI18n)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHTTPMiddleware(ctx, authenticator, baseUserRepository, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	mcpServer, cleanup3, err := mcp.NewServer(ctx, moduleModules)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseRegistry := sse.NewRegistry()
	streamIDResolver := sse.NewStreamResolver(sseRegistry, authenticator, userToken)
	sseServer, cleanup4, err := sse.NewServer(ctx, streamIDResolver, moduleModules, sseRegistry)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transportServer, err := server.NewHTTPServer(ctx, appInfo, httpMiddlewares, moduleModules, authenticator, userToken, registry, mcpServer, sseServer)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcMiddlewares := server.NewGRPCMiddleware(ctx, authenticator, baseUserRepository, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	grpcServer, err := server.NewGRPCServer(ctx, grpcMiddlewares, moduleModules)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	data_Queue := config.ParseQueue(configv1Bootstrap)
	queueQueue, cleanup5, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseJobLogRepository := data.NewBaseJobLogRepository(dataData)
	baseLogRepository := data.NewBaseLogRepository(dataData)
	queueServer, err := queue2.NewServer(queueQueue, baseJobLogRepository, baseLogRepository, moduleModules)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseJobRepository := data.NewBaseJobRepository(dataData)
	jobRegistry, err := job.NewRegistry(moduleModules)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	scheduler := job.NewScheduler(baseJobRepository, jobRegistry)
	jobServer := job.NewServer(scheduler)
	app := newApp(ctx, syncResult, transportServer, grpcServer, mcpServer, sseServer, queueServer, jobServer)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
