// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package kratoscore

import (
	"github.com/go-kratos/kratos/v3"
	biz2 "github.com/liujitcn/kratos-core/internal/biz"
	"github.com/liujitcn/kratos-core/internal/data"
	"github.com/liujitcn/kratos-core/internal/job"
	queue2 "github.com/liujitcn/kratos-core/internal/queue"
	"github.com/liujitcn/kratos-core/internal/resource/i18n"
	"github.com/liujitcn/kratos-core/internal/resource/migration"
	"github.com/liujitcn/kratos-core/internal/resource/openapi"
	"github.com/liujitcn/kratos-core/internal/server"
	"github.com/liujitcn/kratos-core/internal/server/middleware"
	"github.com/liujitcn/kratos-core/internal/sse"
	"github.com/liujitcn/kratos-core/pkg/biz"
	"github.com/liujitcn/kratos-core/pkg/config"
	"github.com/liujitcn/kratos-core/pkg/module"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"
	"github.com/liujitcn/kratos-kit/translator"
)

// Injectors from wire.go:

// NewApplication 通过 Core ProviderSet 装配多个业务模块。
func NewApplication(ctx *bootstrap.Context, modules ...module.Module) (*kratos.App, func(), error) {
	appInfo := config.ParseAppInfo(ctx)
	configv1Bootstrap, err := config.ParseBootstrap(ctx)
	if err != nil {
		return nil, nil, err
	}
	authentication_Jwt, err := config.ParseAuthnJWT(configv1Bootstrap)
	if err != nil {
		return nil, nil, err
	}
	authenticator, err := middleware.NewAuthenticator(authentication_Jwt)
	if err != nil {
		return nil, nil, err
	}
	v, err := config.ParseDatabase(configv1Bootstrap)
	if err != nil {
		return nil, nil, err
	}
	moduleModules := module.NewModules(modules...)
	v2 := module.NewResources(moduleModules)
	models := module.NewModels(v2)
	v3, cleanup, err := biz.NewClients(v, models)
	if err != nil {
		return nil, nil, err
	}
	dataData, err := data.NewData(v3)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseUserRepository := data.NewBaseUserRepository(dataData)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Redis := config.ParseRedis(configv1Bootstrap)
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	moduleI18n := module.NewI18nFromResources(v2)
	i18nI18n, err := i18n.NewI18nCatalog(moduleI18n)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHTTPMiddleware(ctx, authenticator, baseUserRepository, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	openAPI := module.NewOpenAPIFromResources(v2)
	registry, err := openapi.NewRegistry(openAPI)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpRuntime, err := server.NewMCPServer(ctx, moduleModules)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseRegistry := sse.NewRegistry()
	streamIDResolver := sse.NewStreamResolver(sseRegistry, authenticator, userToken)
	transport, err := sse.NewTransport(ctx, streamIDResolver, moduleModules, sseRegistry)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transportServer, err := server.NewHTTPServer(ctx, appInfo, httpMiddlewares, moduleModules, authenticator, userToken, registry, mcpRuntime, transport)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcMiddlewares := server.NewGRPCMiddleware(ctx, authenticator, baseUserRepository, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	grpcServer, err := server.NewGRPCServer(ctx, grpcMiddlewares, moduleModules)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	data_Queue := config.ParseQueue(configv1Bootstrap)
	queueQueue, cleanup3, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseJobLogRepository := data.NewBaseJobLogRepository(dataData)
	baseLogRepository := data.NewBaseLogRepository(dataData)
	queue3, err := queue2.NewQueue(queueQueue, baseJobLogRepository, baseLogRepository, moduleModules)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseJobRepository := data.NewBaseJobRepository(dataData)
	jobRegistry, err := job.NewRegistry(moduleModules)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	scheduler := job.NewScheduler(baseJobRepository, jobRegistry)
	runtime := job.NewRuntime(scheduler)
	v4 := newServers(transportServer, grpcServer, mcpRuntime, transport, queue3, runtime)
	migrations := module.NewMigrations(v2)
	migrationMigration, err := migration.NewMigration(v3, migrations)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseAPIRepository := data.NewBaseAPIRepository(dataData)
	baseAPICase := biz2.NewBaseAPICase(baseAPIRepository)
	baseRoleRepository := data.NewBaseRoleRepository(dataData)
	baseTenantRepository := data.NewBaseTenantRepository(dataData)
	baseTenantCase := biz2.NewBaseTenantCase(dataData, baseRoleRepository, baseTenantRepository)
	casbinRuleRepository := data.NewCasbinRuleRepository(dataData)
	baseMenuRepository := data.NewBaseMenuRepository(dataData)
	casbinRuleCase, err := biz2.NewCasbinRuleCase(casbinRuleRepository, baseMenuRepository, baseRoleRepository, baseTenantRepository, baseAPICase, engine)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseSSE := sse.NewSSE(authenticator, userToken, sseRegistry)
	configv1Pprof := config.ParsePprof(configv1Bootstrap)
	pprofPprof, err := pprof.NewPprof(configv1Pprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configv1Oss := config.ParseOSS(configv1Bootstrap)
	ossOSS, err := oss.NewOSS(configv1Oss)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configv1Translator := config.ParseTranslator(configv1Bootstrap)
	translatorTranslator, err := translator.NewTranslator(configv1Translator)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseCase, cleanup4 := biz.NewBaseCase(ctx, pprofPprof, cacheCache, queueQueue, ossOSS, translatorTranslator, v3)
	app, cleanup5, err := newApplication(ctx, v4, migrationMigration, registry, baseAPICase, baseTenantCase, casbinRuleCase, sseSSE, transport, baseCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
